# amqp-consume
# Autogenerated from man page /usr/share/man/man1/amqp-consume.1.gz
complete -c amqp-consume -s q -l queue -d 'The name of the queue to consume messages from'
complete -c amqp-consume -s e -l exchange -d 'Specifies that an exclusive queue should be declared, and bound to the given …'
complete -c amqp-consume -s r -l routing-key -d 'The routing key for binding.  If omitted, an empty routing key is assumed'
complete -c amqp-consume -s d -l declare -d 'Forces an exclusive queue to be declared, even when it otherwise would not be'
complete -c amqp-consume -s x -l exclusive -d 'Declared queues are non-exclusive by default, this option forces declaration …'
complete -c amqp-consume -s A -l no-ack -d 'Enable "no ack" mode: The AMQP server will unconditionally acknowledge each m…'
complete -c amqp-consume -s c -l count -d 'Stop consuming after the given number of messages have been received'
complete -c amqp-consume -s p -l prefetch-count -d 'Request the server to only send limit messages at a time'
complete -c amqp-consume -l exchange-type -d 'option is used to request the creation of an exchange'
complete -c amqp-consume -o A/--no-ack -d 'is passed, this option has no effect'

