# amqp-publish
# Autogenerated from man page /usr/share/man/man1/amqp-publish.1.gz
complete -c amqp-publish -s e -l exchange -d 'The name of the exchange to publish to'
complete -c amqp-publish -s r -l routing-key -d 'The routing key to publish with.  If omitted, an empty routing key is assumed'
complete -c amqp-publish -s p -l persistent -d 'Use the persistent delivery mode'
complete -c amqp-publish -s C -l content-type -d 'Specifies the content-type property for the message'
complete -c amqp-publish -s E -l content-encoding -d 'Specifies the content-encoding property for the message'
complete -c amqp-publish -s b -l body -d 'Specifies the message body'
complete -c amqp-publish -s H -l header -d 'Specifies an optional header in the form "key: value"'

