# amqp-declare-queue
# Autogenerated from man page /usr/share/man/man1/amqp-declare-queue.1.gz
complete -c amqp-declare-queue -s q -l queue -d 'The name of the queue to declare'
complete -c amqp-declare-queue -s d -l durable -d 'Causes the queue to be declared with the "durable" flag set'

