# augmatch
# Autogenerated from man page /usr/share/man/man1/augmatch.1.gz
complete -c augmatch -s a -l all -d 'X Item "-a, --all" Print all tree nodes, even ones without an associated value'
complete -c augmatch -s e -l exact -d 'X Item "-e, --exact" Only print the parts of the tree that exactly match the …'
complete -c augmatch -s I -l include -d 'X Item "-I, --include=DIR" Add DIR to the module loadpath'
complete -c augmatch -s l -l lens -d 'X Item "-l, --lens=LENS" Use LENS for the given file; without this option, au…'
complete -c augmatch -s L -l print-lens -d 'X Item "-L, --print-lens" Print the name of the lens that will be used with t…'
complete -c augmatch -s m -l match -d 'X Item "-m, --match=EXPR" Only print the parts of the tree that match the pat…'
complete -c augmatch -s r -l root -d 'X Item "-r, --root=ROOT" Use directory ROOT as the root of the filesystem'
complete -c augmatch -s S -l nostdinc -d 'X Item "-S, --nostdinc" Do not search any of the default directories for lens…'
complete -c augmatch -s o -l only-value -d 'X Item "-o, --only-value" Print only the value and not the label or the path …'
complete -c augmatch -s q -l quiet

