# augparse
# Autogenerated from man page /usr/share/man/man1/augparse.1.gz
complete -c augparse -s I -l include -d 'X Item "-I, --include=DIR" Add DIR to the module loadpath'
complete -c augparse -s t -l trace -d 'X Item "-t, --trace" Print a trace of the modules that are being loaded'
complete -c augparse -l nostdinc -d 'X Item "--nostdinc" Do not search any of the default directories for modules'
complete -c augparse -l notypecheck -d 'X Item "--notypecheck" Do not perform lens type checks'
complete -c augparse -l version -d 'X Item "--version" Print version information and exit'
complete -c augparse -s h

