# augprint
# Autogenerated from man page /usr/share/man/man1/augprint.1.gz
complete -c augprint -s v -l verbose -d 'X Item "-v, --verbose" Include the original numbered paths as comments in the…'
complete -c augprint -s p -l pretty -d 'X Item "-p, --pretty" Create more readable output by adding spaces and empty …'
complete -c augprint -s r -o rN -l regexp -l regexp -d 'X Item "-r, -rN, --regexp, --regexp=N" Generate regular expressions to match …'
complete -c augprint -s l -l lens -d 'X Item "-l, --lens=LENS" Use LENS for the given file; without this option, au…'
complete -c augprint -s t -l target -d 'X Item "-t targetfile, --target=targetfile" Generate the script for the FILE …'
complete -c augprint -s s -l noseq

