# diskus
# Autogenerated from man page /usr/share/man/man1/diskus.1.gz
complete -c diskus -s j -l threads -d 'Set the number of threads (default: 3 x num cores)'
complete -c diskus -l size-format -d 'Output format for file sizes (decimal: MB, binary: MiB) [default: decimal] [p…'
complete -c diskus -s v -l verbose -d 'Do not hide filesystem errors'
complete -c diskus -s b -l apparent-size -d 'Compute apparent size instead of disk usage'
complete -c diskus -s h -l help -d 'Prints help information'
complete -c diskus -s V -l version -d 'Prints version information ARGUMENTS'

