# dwarfsextract
# Autogenerated from man page /usr/share/man/man1/dwarfsextract.1.gz
complete -c dwarfsextract -s i -l input -d 'Path to the source filesystem'
complete -c dwarfsextract -s o -l output -d 'If no format is specified, this is the directory to which the contents of the…'
complete -c dwarfsextract -s O -l image-offset -d 'Specify the byte offset at which the filesystem is located in the image'
complete -c dwarfsextract -s f -l format -d 'The archive format to produce'
complete -c dwarfsextract -l continue-on-error -d 'Try to continue with extraction even when errors are encountered'
complete -c dwarfsextract -l disable-integrity-check -d 'This option disables all block integrity checks on the file system data'
complete -c dwarfsextract -l stdout-progress -d 'Write progress percentage to stdout.  Useful for piping to tools like zenity'
complete -c dwarfsextract -s n -l num-workers -d 'Number of worker threads used for extracting the filesystem'
complete -c dwarfsextract -s s -l cache-size -d 'Size of the block cache, in bytes'
complete -c dwarfsextract -s l -l log-level -d 'Specify a logging level'
complete -c dwarfsextract -l log-with-context -d 'Enable logging context regardless of level'
complete -c dwarfsextract -l perfmon -d 'Enable performance monitoring for the list of comma-separated components'
complete -c dwarfsextract -l perfmon-trace -d 'Write JSON trace data for all components enabled by --perfmon to this file wh…'
complete -c dwarfsextract -s h -l help -d 'Show program help, including option defaults'

