# dwarfs
# Autogenerated from man page /usr/share/man/man1/dwarfs.1.gz
complete -c dwarfs -s o -d 'Size of the block cache, in bytes'
complete -c dwarfs -l man -d 'If the project was built with support for built-in manual pages, this option …'

