# dwarfsck
# Autogenerated from man page /usr/share/man/man1/dwarfsck.1.gz
complete -c dwarfsck -s i -l input -d 'Path to the filesystem image'
complete -c dwarfsck -s d -l detail -d 'Level of filesystem information detail.  The default is 2'
complete -c dwarfsck -s q -l quiet -d 'Don\'t produce any output unless there is an error'
complete -c dwarfsck -s v -l verbose -d 'Produce verbose output, where applicable'
complete -c dwarfsck -s O -l image-offset -d 'Specify the byte offset at which the filesystem is located in the image'
complete -c dwarfsck -s H -l print-header -d 'Print the header located before the filesystem image to stdout'
complete -c dwarfsck -s l -l list -d 'List all entries in the file system image.  Uses output similar to tar -t'
complete -c dwarfsck -l checksum -d 'Produce a checksum using the specified algorithm for each regular file in the…'
complete -c dwarfsck -s n -l num-workers -d 'Number of worker threads used for integrity checking'
complete -c dwarfsck -l check-integrity -d 'Instead of performing a fast checksum check, perform a (much slower) integrit…'
complete -c dwarfsck -l no-check -d 'Don\'t even perform a fast checksum check on the file system blocks'
complete -c dwarfsck -s j -l json -d 'Print a simple JSON representation of the filesystem metadata'
complete -c dwarfsck -l export-metadata -d 'Export all filesystem metadata in JSON format'
complete -c dwarfsck -l log-level -d 'Specify a logging level'
complete -c dwarfsck -l log-with-context -d 'Enable logging context regardless of level'
complete -c dwarfsck -s h -l help -d 'Show program help, including option defaults'

