# gobble
# Autogenerated from man page /usr/share/man/man1/gobble.1.gz
complete -c gobble -s h -d 'Displays a friendly help message'
complete -c gobble -s v -d 'Displays the software version'
complete -c gobble -s o -d 'Uses overlap mode which overlays the new window ontop of the old one instead …'

