# guestfs-building
# Autogenerated from man page /usr/share/man/man1/guestfs-building.1.gz
complete -c guestfs-building -l disable-appliance -l disable-daemon
complete -c guestfs-building -l disable-erlang
complete -c guestfs-building -l disable-gobject
complete -c guestfs-building -l disable-golang
complete -c guestfs-building -l disable-haskell
complete -c guestfs-building -l disable-lua
complete -c guestfs-building -l disable-ocaml
complete -c guestfs-building -l disable-perl
complete -c guestfs-building -l disable-php
complete -c guestfs-building -l disable-python
complete -c guestfs-building -l disable-ruby -d 'Disable specific language bindings, even if '
complete -c guestfs-building -l disable-fuse
complete -c guestfs-building -l disable-static
complete -c guestfs-building -l enable-install-daemon
complete -c guestfs-building -l enable-werror
complete -c guestfs-building -l with-default-backend
complete -c guestfs-building -l with-distro
complete -c guestfs-building -l with-extra
complete -c guestfs-building -l version -d 'encode a comma-separated list of facts such as the distro name and version, w…'
complete -c guestfs-building -l without-libvirt
complete -c guestfs-building -l with-qemu
complete -c guestfs-building -l with-supermin-packager-config
complete -c guestfs-building -l with-supermin-extra-options -l opt1 -l opt2

