# guestunmount
# Autogenerated from man page /usr/share/man/man1/guestunmount.1.gz
complete -c guestunmount -l fd -d 'X Item "--fd=FD" Specify the pipe file descriptor to monitor, and delay clean…'
complete -c guestunmount -l help -d 'X Item "--help" Display brief help and exit'
complete -c guestunmount -s q -d 'X Item "-q"'
complete -c guestunmount -l quiet -d 'X Item "--quiet" . PD Donât display error messages from fusermount'
complete -c guestunmount -l no-retry -d 'X Item "--no-retry"'
complete -c guestunmount -l retry -d 'X Item "--retry=N" '
complete -c guestunmount -s V -d 'X Item "-V"'
complete -c guestunmount -l version -d 'Display the program version and exit'

