# guestfs-security
# Autogenerated from man page /usr/share/man/man1/guestfs-security.1.gz
complete -c guestfs-security -l key -d 'code mistakenly uses the MIN\\fR macro instead of MAX\\fR, and therefore only o…'

