# hivexregedit
# Autogenerated from man page /usr/share/man/man1/hivexregedit.1.gz
complete -c hivexregedit -l help -d 'X Item "--help" Display help'
complete -c hivexregedit -l debug -d 'X Item "--debug" Enable debugging in the hivex library'
complete -c hivexregedit -l merge -d 'X Item "--merge" '
complete -c hivexregedit -l export -d 'X Item "--export" '
complete -c hivexregedit -l prefix -d 'X Item "--prefix prefix" Hive files and Windows Registry key names are indire…'
complete -c hivexregedit -l encoding -d 'X Item "--encoding UTF-16LE|ASCII" When merging (only), you may need to speci…'
complete -c hivexregedit -l unsafe-printable-strings -d 'X Item "--unsafe-printable-strings" When exporting (only), assume strings are…'
complete -c hivexregedit -l unsafe -d 'X Item "--unsafe" Use heuristics to tolerate certain levels of corruption wit…'
complete -c hivexregedit -l max-depth

