# hivexsh
# Autogenerated from man page /usr/share/man/man1/hivexsh.1.gz
complete -c hivexsh -s d -d 'X Item "-d" Enable lots of debug messages'
complete -c hivexsh -s f -d 'X Item "-f filename" Read commands from \\f(CW\\*(C`filename\\*(C\' instead of st…'
complete -c hivexsh -s u -d 'X Item "-u" Use heuristics to tolerate certain levels of corruption within hi…'
complete -c hivexsh -s w

