# hivexml
# Autogenerated from man page /usr/share/man/man1/hivexml.1.gz
complete -c hivexml -s d -d 'X Item "-d" Enable lots of debug messages'
complete -c hivexml -s k -d 'X Item "-k" Keep going even if we find errors in the Registry file'
complete -c hivexml -s u

