# kqml
# Autogenerated from man page /usr/share/man/man1/kqml.1.gz
complete -c kqml -s v -l version -d 'Displays version information'
complete -c kqml -s d -l domain -d 'The main localization domain'
complete -c kqml -s h -l help -d 'Displays this help'

