# libguestfs-test-tool
# Autogenerated from man page /usr/share/man/man1/libguestfs-test-tool.1.gz
complete -c libguestfs-test-tool -l help -d 'X Item "--help" Display short usage information and exit'
complete -c libguestfs-test-tool -l qemu -d 'X Item "--qemu qemu_binary" If you have downloaded another qemu binary, point…'
complete -c libguestfs-test-tool -l qemudir -d 'X Item "--qemudir qemu_source_dir" If you have compiled qemu from source, poi…'
complete -c libguestfs-test-tool -s t -d 'X Item "-t N"'
complete -c libguestfs-test-tool -l timeout -d 'X Item "--timeout N" . PD Set the launch timeout to \\f(CW\\*(C`N\\*(C\' seconds'
complete -c libguestfs-test-tool -s V -d 'X Item "-V"'
complete -c libguestfs-test-tool -l version -d 'Display the libguestfs version number and exit'

