# libguestfs-make-fixed-appliance
# Autogenerated from man page /usr/share/man/man1/libguestfs-make-fixed-appliance.1.gz
complete -c libguestfs-make-fixed-appliance -l help -d 'X Item "--help" Display short usage information and exit'
complete -c libguestfs-make-fixed-appliance -s V -d 'X Item "-V"'
complete -c libguestfs-make-fixed-appliance -l version -d 'X Item "--version" . PD Display the version number and exit'
complete -c libguestfs-make-fixed-appliance -l xz

