# swtpm-create-tpmca
# Autogenerated from man page /usr/share/man/man8/swtpm-create-tpmca.8.gz
complete -c swtpm-create-tpmca -l dir
complete -c swtpm-create-tpmca -l overwrite
complete -c swtpm-create-tpmca -l register
complete -c swtpm-create-tpmca -l key-password
complete -c swtpm-create-tpmca -l srk-password
complete -c swtpm-create-tpmca -l outfile
complete -c swtpm-create-tpmca -l owner
complete -c swtpm-create-tpmca -l group
complete -c swtpm-create-tpmca -l tss-tcsd-hostname
complete -c swtpm-create-tpmca -o tss-tcsd-port
complete -c swtpm-create-tpmca -l tpm2
complete -c swtpm-create-tpmca -l pid
complete -c swtpm-create-tpmca -o help -s h -s '?'

