# virt-cat
# Autogenerated from man page /usr/share/man/man1/virt-cat.1.gz
complete -c virt-cat -l help -d 'X Item "--help" Display brief help'
complete -c virt-cat -s a -d 'X Item "-a file"'
complete -c virt-cat -l add -d 'X Item "--add file" '
complete -c virt-cat -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-cat -s c -d 'X Item "-c URI"'
complete -c virt-cat -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-cat -s d -d 'X Item "-d guest"'
complete -c virt-cat -l domain -d 'X Item "--domain guest" . PD Add all the disks from the named libvirt guest'
complete -c virt-cat -l echo-keys -d 'X Item "--echo-keys" When prompting for keys and passphrases, virt-cat normal…'
complete -c virt-cat -l format -d 'X Item "--format=raw|qcow2|. "'
complete -c virt-cat -l key -d 'X Item "--key SELECTOR" Specify a key for LUKS, to automatically open a LUKS …'
complete -c virt-cat -l keys-from-stdin -d 'X Item "--keys-from-stdin" Read key or passphrase parameters from stdin'
complete -c virt-cat -s m -d 'X Item "-m dev[:mountpoint[:options[:fstype]]]"'
complete -c virt-cat -l mount -d 'X Item "--mount dev[:mountpoint[:options[:fstype]]]" '
complete -c virt-cat -s v -d 'X Item "-v"'
complete -c virt-cat -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-cat -s V -d 'X Item "-V"'
complete -c virt-cat -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-cat -s x

