# virt-alignment-scan
# Autogenerated from man page /usr/share/man/man1/virt-alignment-scan.1.gz
complete -c virt-alignment-scan -l help -d 'X Item "--help" Display brief help'
complete -c virt-alignment-scan -s a -d 'X Item "-a file"'
complete -c virt-alignment-scan -l add -d 'X Item "--add file" '
complete -c virt-alignment-scan -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-alignment-scan -s c -d 'X Item "-c URI"'
complete -c virt-alignment-scan -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-alignment-scan -s d -d 'X Item "-d guest"'
complete -c virt-alignment-scan -l domain -d 'X Item "--domain guest" . PD Add all the disks from the named libvirt guest'
complete -c virt-alignment-scan -l format -d 'X Item "--format=raw|qcow2|. "'
complete -c virt-alignment-scan -s P -d 'X Item "-P nr_threads" Since libguestfs 1'
complete -c virt-alignment-scan -s q -d 'X Item "-q"'
complete -c virt-alignment-scan -l quiet -d 'X Item "--quiet" . PD Donât produce any output'
complete -c virt-alignment-scan -l uuid -d 'X Item "--uuid" Print UUIDs instead of names'
complete -c virt-alignment-scan -s v -d 'X Item "-v"'
complete -c virt-alignment-scan -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-alignment-scan -s V -d 'X Item "-V"'
complete -c virt-alignment-scan -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-alignment-scan -s x

