# virt-log
# Autogenerated from man page /usr/share/man/man1/virt-log.1.gz
complete -c virt-log -l help -d 'X Item "--help" Display brief help'
complete -c virt-log -s a -d 'X Item "-a file"'
complete -c virt-log -l add -d 'X Item "--add file" '
complete -c virt-log -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-log -s c -d 'X Item "-c URI"'
complete -c virt-log -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-log -s d -d 'X Item "-d guest"'
complete -c virt-log -l domain -d 'X Item "--domain guest" . PD Add all the disks from the named libvirt guest'
complete -c virt-log -l echo-keys -d 'X Item "--echo-keys" When prompting for keys and passphrases, virt-log normal…'
complete -c virt-log -l format -d 'X Item "--format=raw|qcow2|. "'
complete -c virt-log -l key -d 'X Item "--key SELECTOR" Specify a key for LUKS, to automatically open a LUKS …'
complete -c virt-log -l keys-from-stdin -d 'X Item "--keys-from-stdin" Read key or passphrase parameters from stdin'
complete -c virt-log -s v -d 'X Item "-v"'
complete -c virt-log -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-log -s V -d 'X Item "-V"'
complete -c virt-log -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-log -s x

