# virt-builder-repository
# Autogenerated from man page /usr/share/man/man1/virt-builder-repository.1.gz
complete -c virt-builder-repository -l help -d 'X Item "--help" Display help'
complete -c virt-builder-repository -l gpg -d 'X Item "--gpg GPG" Specify an alternate gpg\\|(1) (GNU Privacy Guard) binary'
complete -c virt-builder-repository -s K -d 'X Item "-K KEYID"'
complete -c virt-builder-repository -l gpg-key -d 'X Item "--gpg-key KEYID" '
complete -c virt-builder-repository -s i -d 'X Item "-i"'
complete -c virt-builder-repository -l interactive -d 'X Item "--interactive" . PD Prompt for missing data'
complete -c virt-builder-repository -l no-compression -d 'X Item "--no-compression" Donât compress the template images'
complete -c virt-builder-repository -l machine-readable -d 'X Item "--machine-readable"'
complete -c virt-builder-repository -l colors -d 'X Item "--colors"'
complete -c virt-builder-repository -l colours -d 'X Item "--colours" . PD Use ANSI colour sequences to colourize messages'
complete -c virt-builder-repository -s q -d 'X Item "-q"'
complete -c virt-builder-repository -l quiet -d 'X Item "--quiet" . PD Donât print ordinary progress messages'
complete -c virt-builder-repository -s v -d 'X Item "-v"'
complete -c virt-builder-repository -l verbose -d 'X Item "--verbose" . PD Enable debug messages and/or produce verbose output'
complete -c virt-builder-repository -s V -d 'X Item "-V"'
complete -c virt-builder-repository -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-builder-repository -l wrap -d 'X Item "--wrap" Wrap error, warning, and informative messages'
complete -c virt-builder-repository -l default-key -d fingerprint
complete -c virt-builder-repository -s x

