# virt-sysprep
# Autogenerated from man page /usr/share/man/man1/virt-sysprep.1.gz
complete -c virt-sysprep -l help -d 'X Item "--help" Display brief help'
complete -c virt-sysprep -s a -d 'X Item "-a file"'
complete -c virt-sysprep -l add -d 'X Item "--add file" '
complete -c virt-sysprep -l colors -d 'X Item "--colors"'
complete -c virt-sysprep -l colours -d 'X Item "--colours" . PD Use ANSI colour sequences to colourize messages'
complete -c virt-sysprep -s c -d 'X Item "-c URI"'
complete -c virt-sysprep -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-sysprep -s d -d 'X Item "-d guest"'
complete -c virt-sysprep -l domain -d 'X Item "--domain guest" . PD Add all the disks from the named libvirt guest'
complete -c virt-sysprep -s n -d 'X Item "-n"'
complete -c virt-sysprep -l dry-run -d 'X Item "--dry-run" . PD Perform a read-only "dry run" on the guest'
complete -c virt-sysprep -l enable -d 'X Item "--enable operations" Choose which sysprep operations to perform'
complete -c virt-sysprep -l operation -d 'X Item "--operation operations"'
complete -c virt-sysprep -l operations -d 'X Item "--operations operations" '
complete -c virt-sysprep -l echo-keys -d 'X Item "--echo-keys" When prompting for keys and passphrases, virt-sysprep no…'
complete -c virt-sysprep -l format -d 'X Item "--format raw|qcow2|. "'
complete -c virt-sysprep -l key -d 'X Item "--key SELECTOR" Specify a key for LUKS, to automatically open a LUKS …'
complete -c virt-sysprep -l keys-from-stdin -d 'X Item "--keys-from-stdin" Read key or passphrase parameters from stdin'
complete -c virt-sysprep -l list-operations -d 'X Item "--list-operations" List the operations supported by the virt-sysprep …'
complete -c virt-sysprep -l mount-options -d 'X Item "--mount-options mp:opts[;mp:opts;'
complete -c virt-sysprep -s q -d 'X Item "-q"'
complete -c virt-sysprep -l quiet -d 'X Item "--quiet" . PD Donât print log messages'
complete -c virt-sysprep -l network -d 'X Item "--network"'
complete -c virt-sysprep -l no-network -d 'X Item "--no-network" '
complete -c virt-sysprep -s v -d 'X Item "-v"'
complete -c virt-sysprep -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-sysprep -s V -d 'X Item "-V"'
complete -c virt-sysprep -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-sysprep -l wrap -d 'X Item "--wrap" Wrap error, warning, and informative messages'
complete -c virt-sysprep -s x -d 'X Item "-x" Enable tracing of libguestfs API calls. ie n'
complete -c virt-sysprep -l append-line -d el
complete -c virt-sysprep -l chmod -d el
complete -c virt-sysprep -l chown -d el
complete -c virt-sysprep -l commands-from-file -d el
complete -c virt-sysprep -l copy -d el
complete -c virt-sysprep -l copy-in -d el
complete -c virt-sysprep -l delete -d el
complete -c virt-sysprep -l edit -d el
complete -c virt-sysprep -l firstboot -d el
complete -c virt-sysprep -l firstboot-command -d el
complete -c virt-sysprep -l firstboot-install -d el
complete -c virt-sysprep -l hostname -d el
complete -c virt-sysprep -l inject-qemu-ga -d el
complete -c virt-sysprep -l inject-virtio-win -d el
complete -c virt-sysprep -l install -d el
complete -c virt-sysprep -l keep-user-accounts -d el
complete -c virt-sysprep -l link -d el
complete -c virt-sysprep -l mkdir -d el
complete -c virt-sysprep -l move -d el
complete -c virt-sysprep -l no-logfile -d el
complete -c virt-sysprep -l no-selinux-relabel -d el
complete -c virt-sysprep -l password -d el
complete -c virt-sysprep -l password-crypto -d el
complete -c virt-sysprep -l remove-user-accounts -d el
complete -c virt-sysprep -l root-password -d el
complete -c virt-sysprep -l run -d el
complete -c virt-sysprep -l run-command -d el
complete -c virt-sysprep -l script -d el
complete -c virt-sysprep -l scriptdir -d el
complete -c virt-sysprep -l scrub -d el
complete -c virt-sysprep -l selinux-relabel -d el
complete -c virt-sysprep -l sm-attach -d el
complete -c virt-sysprep -l sm-credentials -d el
complete -c virt-sysprep -l sm-register -d el
complete -c virt-sysprep -l sm-remove -d el
complete -c virt-sysprep -l sm-unregister -d el
complete -c virt-sysprep -l ssh-inject -d el
complete -c virt-sysprep -l tar-in -d el
complete -c virt-sysprep -l timezone -d el
complete -c virt-sysprep -l touch -d el
complete -c virt-sysprep -l truncate -d el
complete -c virt-sysprep -l truncate-recursive -d el
complete -c virt-sysprep -l uninstall -d el
complete -c virt-sysprep -l update -d el
complete -c virt-sysprep -l upload -d el
complete -c virt-sysprep -l write -d el
complete -c virt-sysprep -l enable/--operations -d 'Use a comma-separated list, for example:  virt-sysprep --operations ssh-hostk…'

