# virt-make-fs
# Autogenerated from man page /usr/share/man/man1/virt-make-fs.1.gz
complete -c virt-make-fs -l help -d 'X Item "--help" Display brief help'
complete -c virt-make-fs -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-make-fs -l floppy -d 'X Item "--floppy" Create a virtual floppy disk'
complete -c virt-make-fs -l size -d 'X Item "--size=N"'
complete -c virt-make-fs -s s -d 'X Item "-s N"'
complete -c virt-make-fs -l format -d 'X Item "--format=FMT"'
complete -c virt-make-fs -s F -d 'X Item "-F FMT" . PD Choose the output disk image format'
complete -c virt-make-fs -l type -d 'X Item "--type=FS"'
complete -c virt-make-fs -s t -d 'X Item "-t FS" . PD Choose the output filesystem type'
complete -c virt-make-fs -l label -d 'X Item "--label=LABEL" Set the filesystem label'
complete -c virt-make-fs -l partition -d 'X Item "--partition"'
complete -c virt-make-fs -s v -d 'X Item "-v"'
complete -c virt-make-fs -l verbose -d 'X Item "--verbose" . PD Enable debugging information'
complete -c virt-make-fs -s V -d 'X Item "-V"'
complete -c virt-make-fs -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-make-fs -s x

