# virt-tail
# Autogenerated from man page /usr/share/man/man1/virt-tail.1.gz
complete -c virt-tail -l help -d 'X Item "--help" Display brief help'
complete -c virt-tail -s a -d 'X Item "-a file"'
complete -c virt-tail -l add -d 'X Item "--add file" '
complete -c virt-tail -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-tail -s c -d 'X Item "-c URI"'
complete -c virt-tail -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-tail -s d -d 'X Item "-d guest"'
complete -c virt-tail -l domain -d 'X Item "--domain guest" . PD Add all the disks from the named libvirt guest'
complete -c virt-tail -l echo-keys -d 'X Item "--echo-keys" When prompting for keys and passphrases, virt-tail norma…'
complete -c virt-tail -s f -d 'X Item "-f"'
complete -c virt-tail -l follow -d 'X Item "--follow" . PD This option is ignored'
complete -c virt-tail -l format -d 'X Item "--format=raw|qcow2|. "'
complete -c virt-tail -l key -d 'X Item "--key SELECTOR" Specify a key for LUKS, to automatically open a LUKS …'
complete -c virt-tail -l keys-from-stdin -d 'X Item "--keys-from-stdin" Read key or passphrase parameters from stdin'
complete -c virt-tail -s m -d 'X Item "-m dev[:mountpoint[:options[:fstype]]]"'
complete -c virt-tail -l mount -d 'X Item "--mount dev[:mountpoint[:options[:fstype]]]" '
complete -c virt-tail -s v -d 'X Item "-v"'
complete -c virt-tail -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-tail -s V -d 'X Item "-V"'
complete -c virt-tail -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-tail -s x

