# virt-win-reg
# Autogenerated from man page /usr/share/man/man1/virt-win-reg.1.gz
complete -c virt-win-reg -l help -d 'X Item "--help" Display brief help'
complete -c virt-win-reg -l version -d 'X Item "--version" Display version number and exit'
complete -c virt-win-reg -l debug -d 'X Item "--debug" Enable debugging messages'
complete -c virt-win-reg -s c -d 'X Item "-c URI"'
complete -c virt-win-reg -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-win-reg -l format -d 'X Item "--format raw" Specify the format of disk images given on the command …'
complete -c virt-win-reg -l merge -d 'X Item "--merge" In merge mode, this merges a textual regedit file into the W…'
complete -c virt-win-reg -l encoding -d 'X Item "--encoding UTF-16LE|ASCII" When merging (only), you may need to speci…'
complete -c virt-win-reg -l unsafe-printable-strings -d 'X Item "--unsafe-printable-strings" When exporting (only), assume strings are…'

