# virt-format
# Autogenerated from man page /usr/share/man/man1/virt-format.1.gz
complete -c virt-format -l help -d 'X Item "--help" Display brief help'
complete -c virt-format -s a -d 'X Item "-a file"'
complete -c virt-format -l add -d 'X Item "--add file" '
complete -c virt-format -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-format -l filesystem -d 'X Item "--filesystem=ext3|ntfs|vfat|'
complete -c virt-format -l format -d 'X Item "--format=raw|qcow2|. "'
complete -c virt-format -l label -d 'X Item "--label=LABEL" Set the filesystem label'
complete -c virt-format -l lvm -d 'X Item "--lvm=/dev/VG/LV" Create a Linux LVM2 logical volume called /dev/VG/LV'
complete -c virt-format -l partition -d 'X Item "--partition" Create either an MBR or GPT partition covering the whole…'
complete -c virt-format -s v -d 'X Item "-v"'
complete -c virt-format -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-format -s V -d 'X Item "-V"'
complete -c virt-format -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-format -l wipe -d 'X Item "--wipe" Normally virt-format does not wipe data from the disk (becaus…'
complete -c virt-format -s x

