# virt-index-validate
# Autogenerated from man page /usr/share/man/man1/virt-index-validate.1.gz
complete -c virt-index-validate -l 'compat-1.24.0' -d 'X Item "--compat-1. 24. 0" Check for compatibility with virt-builder 1. 24. 0'
complete -c virt-index-validate -l 'compat-1.24.1' -d 'X Item "--compat-1. 24. 1" Check for compatibility with virt-builder â¥ 1'
complete -c virt-index-validate -l help -d 'X Item "--help" Display help'
complete -c virt-index-validate -s V -d 'X Item "-V"'
complete -c virt-index-validate -l version -d 'Display version number and exit.  EXIT STATUS'

