# virt-inspector
# Autogenerated from man page /usr/share/man/man1/virt-inspector.1.gz
complete -c virt-inspector -l help -d 'X Item "--help" Display brief help'
complete -c virt-inspector -s a -d 'X Item "-a file"'
complete -c virt-inspector -l add -d 'X Item "--add file" '
complete -c virt-inspector -l blocksize -d 'X Item "--blocksize=512"'
complete -c virt-inspector -s c -d 'X Item "-c URI"'
complete -c virt-inspector -l connect -d 'X Item "--connect URI" . PD If using libvirt, connect to the given URI'
complete -c virt-inspector -s d -d 'X Item "-d guest"'
complete -c virt-inspector -l domain -d 'X Item "--domain guest" . PD Add all the disks from the named libvirt guest'
complete -c virt-inspector -l echo-keys -d 'X Item "--echo-keys" When prompting for keys and passphrases, virt-inspector …'
complete -c virt-inspector -l format -d 'X Item "--format=raw|qcow2|. "'
complete -c virt-inspector -l key -d 'X Item "--key SELECTOR" Specify a key for LUKS, to automatically open a LUKS …'
complete -c virt-inspector -l keys-from-stdin -d 'X Item "--keys-from-stdin" Read key or passphrase parameters from stdin'
complete -c virt-inspector -l no-applications -d 'X Item "--no-applications" By default the output of virt-inspector includes t…'
complete -c virt-inspector -l no-icon -d 'X Item "--no-icon" By default the output of virt-inspector includes the icon …'
complete -c virt-inspector -s v -d 'X Item "-v"'
complete -c virt-inspector -l verbose -d 'X Item "--verbose" . PD Enable verbose messages for debugging'
complete -c virt-inspector -s V -d 'X Item "-V"'
complete -c virt-inspector -l version -d 'X Item "--version" . PD Display version number and exit'
complete -c virt-inspector -s x -d 'X Item "-x" Enable tracing of libguestfs API calls'
complete -c virt-inspector -l xpath

